### ISSUE TITLE
FormElements (example) -> Button + Icon example is not correct (Login with github or Login with Twitter examples)

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#350]
Daisyui:
![image](https://user-images.githubusercontent.com/42554876/234066898-753a5b30-af3a-45b2-9dc8-7c34b1e5889a.png)

Tabler:
![image](https://user-images.githubusercontent.com/42554876/234066773-c7c3f8f4-adca-4573-bf4f-16b104ea82e0.png)

**Comment by saadeghi** [comment]
@TheHadiAhmadi  
I fixed the overflow issue but the problem is, daisyUI buttons (with default size) are larger comparing to Tabler buttons and have bigger and bolder text. I would suggest using a shorter text for this specific example or put the buttons under each other because we can't fit these 2 large buttons with icon and these long texts in this small area.
<img width="464" alt="Screenshot 2023-05-03 at 19 59 29" src="https://user-images.githubusercontent.com/7342023/235987240-e5312302-4452-426a-bfb9-65a5232604fc.png">
